
import Head from 'next/head'
import AboutSection from '../components/aboutSection/aboutSection'
import Contact from '../components/ contact/contact'
import Herobanner from '../components/Herobanner/herobanner'
import ImageSection from '../components/imageSection/ImageSection'

import styles from '../styles/Home.module.css'
import Footer from '../components/footer'

export default function Home() {

  return (
    <div className={styles.container}>
      <Head>
        <title>Liv MATHILDE MECHIN</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Herobanner />
      <AboutSection /> 
      <ImageSection />
      <Contact />

      <Footer />
    
    </div>
  )
}
